---
apiVersion: v2
name: dagster
version: 0.14.7
kubeVersion: ">= 1.18.0-0"
description: The data orchestration platform built for productivity.
type: application
keywords:
  - analytics
  - data-orchestrator
  - data-pipelines
  - etl
  - workflow
sources:
  - https://github.com/dagster-io/dagster/tree/master/helm/dagster
dependencies:
  - name: dagster-user-deployments
    version: 0.14.7
    condition: dagster-user-deployments.enableSubchart
  - name: postgresql
    version: 8.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.16.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 12.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.internal
maintainers:
  - name: Elementl
    email: support@elementl.com
    url: https://elementl.com
icon: https://elementl.com/icons/social/dagster.jpg
appVersion: dev
